### ISSUE TITLE
bamliquidator_regions error

### ISSUE THREAD

**Issue by venuthatikonda** [BradnerLab/pipeline#61]
Hi,
I'm trying to use `ROSE2_main.py` script on my data. But at one point the script is returning the following error.

```
Liquidation completed: 0.117097 seconds
Traceback (most recent call last):
  File "/scripts/tools/pipeline/bamliquidator_internal/bamliquidatorbatch/bamliquidator_batch.py", line 532, in <module>
    main()
  File "/scripts/tools/pipeline/bamliquidator_internal/bamliquidatorbatch/bamliquidator_batch.py", line 512, in main
    not args.quiet, args.number_of_threads)
  File "/scripts/tools/pipeline/bamliquidator_internal/bamliquidatorbatch/bamliquidator_batch.py", line 314, in __init__
    self.batch(extension, sense)
  File "/scripts/tools/pipeline/bamliquidator_internal/bamliquidatorbatch/bamliquidator_batch.py", line 205, in batch
    raise Exception("%s failed with exit code %d" % (self.executable_path, return_code))
Exception: /scripts/tools/pipeline/bamliquidator_internal/bamliquidator_regions failed with exit code -6
```
I tried `bamliquidator_btach.py` script separately, it is also returning the same error. It would be really helpful if you can suggest some fixes for this issue.

Thank you.

**Comment by jdimatteo** [comment]
@venuthatikonda can you please post or email me (jdimatteo@gmail.com) your output/log.txt file?  it should be in the directory you ran ROSE2_main.py from
