### ISSUE TITLE
bamliquidator_batch ValueError: cannot set WRITEABLE flag to True of this array

### ISSUE THREAD

**Issue by raphaelbetschart** [BradnerLab/pipeline#79]
When trying to run bamliquidator_batch on Ubuntu 18.04, I get the following error:

Traceback (most recent call last):
  File "/usr/bin/bamliquidator_batch", line 11, in <module>
    load_entry_point('BamLiquidatorBatch==1.3.8', 'console_scripts', 'bamliquidator_batch')()
  File "/usr/lib/python2.7/dist-packages/bamliquidatorbatch/bamliquidator_batch.py", line 503, in main
    not args.quiet, args.number_of_threads, args.black_list)
  File "/usr/lib/python2.7/dist-packages/bamliquidatorbatch/bamliquidator_batch.py", line 254, in __init__
    include_cpp_warnings_in_stderr, counts_file_path, number_of_threads)
  File "/usr/lib/python2.7/dist-packages/bamliquidatorbatch/bamliquidator_batch.py", line 133, in __init__
    self.bam_file_paths = bam_file_paths_with_no_file_entries(file_names, self.bam_file_paths)
  File "/usr/lib/python2.7/dist-packages/bamliquidatorbatch/bamliquidator_batch.py", line 61, in bam_file_paths_with_no_file_entries
    if basename(bam_file_path) not in file_names:
  File "/home/raphaelb/.local/lib/python2.7/site-packages/six.py", line 566, in next
    return type(self).__next__(self)
  File "/usr/lib/python2.7/dist-packages/tables/vlarray.py", line 624, in __next__
    self.listarr = self.read(self._startb, self._stopb, self._step)
  File "/usr/lib/python2.7/dist-packages/tables/vlarray.py", line 811, in read
    listarr = self._read_array(start, stop, step)
  File "tables/hdf5extension.pyx", line 2106, in tables.hdf5extension.VLArray._read_array
ValueError: cannot set WRITEABLE flag to True of this array
Closing remaining open files:output/counts.h5...done

I installed bamliquidator with apt-get. The output of the commands specified in the troubleshooting sections are:

bamliquidator_batch 1.3.8
Version: 1.3.8-0ppa1~bionic
/usr/bin/bamliquidator_batch
/usr/bin/bamliquidator_bins
/usr/bin/bamliquidator_regions

**Comment by raphaelbetschart** [comment]
Was able to fix it. The problem was a specific numpy version had a bug with a specific pytables version. I ran "python2 -m pip install numpy==1.15.4"
